name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        # Previously actions/checkout@v4
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          submodules: true

      - name: Setup Hugo
        # Previously peaceiris/actions-hugo@v3
        uses: peaceiris/actions-hugo@c6203115c54ec47de51b038c9c05e19bd8dc0716
        with:
          hugo-version: '0.128.0'
          extended: true

      - name: Build Hugo Site
        run: hugo --gc --minify

      - name: Deploy to Cloudflare Pages
        # Previously cloudflare/wrangler-action@v3
        uses: cloudflare/wrangler-action@392082e817b2eb071ebdb5001ea332d5b72221b2
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy public --project-name="thecosmicmicrowavewebsite"
